spring.application.name=ORM

# 1. C?u hình k?t n?i Database (Thay ??i username và password cho kh?p v?i máy c?a b?n)
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management
spring.datasource.username=postgres
spring.datasource.password=lehqwuoc
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. C?u hình c? ch? t? ??ng t?o/c?p nh?t b?ng d? li?u d?a trên Entity
spring.jpa.hibernate.ddl-auto=update

# 3. Hi?n th? các câu l?nh SQL mà Hibernate t? sinh ra d??i màn hình Console ?? ti?n theo dõi
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. ??nh ngh?a c?u trúc SQL t?i ?u riêng cho PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
